version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "REUSE.toml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "tests/dmi/DMI-amd",
 "tests/dmi/DMI-upboard"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"
